services:
  mysql:
    user: "${UID}:${GID}"
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DB: tws_db
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - 2tier
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  flaskapp:
    build:
      context: .
    container_name: flaskapp
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DB: tws_db
    networks:
      - 2tier
    ports:
      - "5000:5000"
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

networks:
  2tier:
